# Generated by Django 3.2.23 on 2023-12-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_shell_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
